CREATE PROC FI_SP_IncBenef
	@NOME VARCHAR(255),
	@CPF VARCHAR(11),
	@IDCLIENTE INT
AS
BEGIN
	INSERT INTO BENEFICIARIOS (NOME, CPF, IDCLIENTE)
	VALUES (@NOME, @CPF, @IDCLIENTE)

	SELECT SCOPE_IDENTITY()
END